# Generated by Django 3.0.2 on 2020-01-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekarze', '0003_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
