# Generated by Django 3.0.2 on 2020-01-25 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lekarze', '0007_shiftcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftcounter',
            name='shift_Type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lekarze.ShiftType'),
            preserve_default=False,
        ),
    ]
