# Generated by Django 3.0.2 on 2020-01-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lekarze', '0008_shiftcounter_shift_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftcounter',
            old_name='shift_Type',
            new_name='shift_type',
        ),
    ]
