# Generated by Django 3.0.2 on 2020-01-26 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lekarze', '0010_shifttype_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifttype',
            name='department',
        ),
        migrations.AddField(
            model_name='shiftcounter',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lekarze.Department'),
            preserve_default=False,
        ),
    ]
