# Generated by Django 3.0.2 on 2020-01-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lekarze', '0012_auto_20200126_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftcounter',
            name='department',
        ),
    ]
