# Generated by Django 3.0.2 on 2020-01-26 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lekarze', '0015_exchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='shift',
        ),
        migrations.AddField(
            model_name='exchange',
            name='myshift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='myshift', to='lekarze.Shift'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='yourshift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yourshift', to='lekarze.Shift'),
        ),
    ]
